In [7]:
import genFaceDataset
gfd = genFaceDataset.genFaceDataset()

In [8]:
gfd.setFrameStep(10)

'success'

In [2]:
gfd.setVideo("classvid1-0.mp4", "../videos/classvid/classvid1/", 
    outputDir="../videos/classvid-processed/classvid1",version="0")

NameError: name 'gfd' is not defined

In [10]:
for i in range(6,7):
    gfd.cleanUpSpecific("classvid1-" + str(i) + ".mp4",
        outputDir="../videos/classvid-processed/classvid1/",version="0")

2 videos ../videos/classvid-processed/classvid1/processed-classvid1-6-version-0/13 is noise
1 videos ../videos/classvid-processed/classvid1/processed-classvid1-6-version-0/15 is noise
1 videos ../videos/classvid-processed/classvid1/processed-classvid1-6-version-0/14 is noise
1 videos ../videos/classvid-processed/classvid1/processed-classvid1-6-version-0/16 is noise


In [9]:
for i in range(6,7):
    print("classvid1-" + str(i) + ".mp4", "../videos/classvid/classvid1/")
    gfd.genFromVideo("classvid1-" + str(i) + ".mp4", "../videos/classvid/classvid1/",
    outputDir="../videos/classvid-processed/classvid1",version="0")

classvid1-6.mp4 ../videos/classvid/classvid1/
file:  ../videos/classvid/classvid1/classvid1-6.mp4
 frame: 0
 frame: 1
 frame: 2
 frame: 3
 frame: 4
 frame: 5
 frame: 6
 frame: 7
0
../videos/classvid-processed/classvid1/processed-classvid1-6-version-0/0/
1
../videos/classvid-processed/classvid1/processed-classvid1-6-version-0/1/
2
../videos/classvid-processed/classvid1/processed-classvid1-6-version-0/2/
3
../videos/classvid-processed/classvid1/processed-classvid1-6-version-0/3/
4
../videos/classvid-processed/classvid1/processed-classvid1-6-version-0/4/
5
../videos/classvid-processed/classvid1/processed-classvid1-6-version-0/5/
6
../videos/classvid-processed/classvid1/processed-classvid1-6-version-0/6/
7
../videos/classvid-processed/classvid1/processed-classvid1-6-version-0/7/
8
../videos/classvid-processed/classvid1/processed-classvid1-6-version-0/8/
9
../videos/classvid-processed/classvid1/processed-classvid1-6-version-0/9/
10
../videos/classvid-processed/classvid1/processed-classvid1-

In [ ]:
gfd.genFromVideo("classvid1-7.mp4", "../videos/classvid/classvid1/",
    outputDir="../videos/classvid-processed/classvid1",version="0")

In [4]:
gfd.cleanUp()

1 videos ../videos/classvid-processed/classvid1processed-classvid1-0-version-0/8 is noise
1 videos ../videos/classvid-processed/classvid1processed-classvid1-0-version-0/5 is noise
1 videos ../videos/classvid-processed/classvid1processed-classvid1-0-version-0/7 is noise
1 videos ../videos/classvid-processed/classvid1processed-classvid1-0-version-0/3 is noise
1 videos ../videos/classvid-processed/classvid1processed-classvid1-0-version-0/4 is noise
1 videos ../videos/classvid-processed/classvid1processed-classvid1-0-version-0/9 is noise
1 videos ../videos/classvid-processed/classvid1processed-classvid1-0-version-0/2 is noise
1 videos ../videos/classvid-processed/classvid1processed-classvid1-0-version-0/6 is noise
1 videos ../videos/classvid-processed/classvid1processed-classvid1-0-version-0/0 is noise
1 videos ../videos/classvid-processed/classvid1processed-classvid1-0-version-0/10 is noise
1 videos ../videos/classvid-processed/classvid1processed-classvid1-0-version-0/1 is noise


'success'

In [2]:
import cv2
import matplotlib.pyplot as plt

im = cv2.imread("sample.png")

In [3]:
import getMultiAlignment

gma = getMultiAlignment.MultifaceAlignment()

In [5]:
faceBoxes, alignedFaces = gma.getAlignments(im, mode="all")

In [8]:
print(faceBoxes[0])

[182.87337844 854.72192445 245.29213805 917.14068407   0.99999726]


In [5]:
def drawBox(image, box, draw=None):
    print(box[0],box[1])
    _image = image.copy()
    if draw:
        
        _image = cv2.rectangle(_image,(int(box[0]),int(box[1])), (int(box[2]), int(box[3])),(0,255,0),2)
    cv2.imshow("f",_image)
#     plt.imshow(_image)
#     plt.show()

In [1]:
def drawFromBox(image, box):
    print(box[0],box[1])
    _image = image.copy()
    if draw:
        _image = cv2.rectangle(_image,(int(box[0]),int(box[1])), (int(box[2]), int(box[3])),(0,255,0),2)
    plt.imshow(_image[box[1:3,0:2]])
    plt.show()

In [1]:
drawBox(alignedFaces[3], faceBoxes[2], draw=None)

NameError: name 'drawBox' is not defined

In [ ]:
drawBox(im, faceBoxes[3], draw=True)

In [ ]:
import numpy as np
a = [257.15174742 337.18087175 274.41724607 354.44637041   0.99999905]


In [24]:
gfd.genFromVideo("C0009.MP4", "../videos/",version="3")

 frame: 0
 frame: 1
 frame: 2
 frame: 3
 frame: 4
 frame: 5
 frame: 6
 frame: 7
 frame: 8
 frame: 9


KeyboardInterrupt: 

In [2]:
for faces in gfd.personBoxDict:
    print(len(gfd.personBoxDict[faces]))

In [5]:
gfd.personBoxDict[0]

[array([256.74750765, 337.577285  , 274.99542002, 355.82519737,
          0.99999869]),
 array([257.01059432, 337.18251153, 274.45035072, 354.62226793,
          0.99999797]),
 array([256.89072171, 337.56544265, 274.33300898, 355.00772992,
          0.99999821]),
 array([256.5726971 , 337.88484023, 274.77225796, 356.08440109,
          0.99999952]),
 array([256.52934411, 337.86323241, 274.78762656, 356.12151486,
          0.9999994 ]),
 array([256.38200323, 337.76539511, 274.87242057, 356.25581246,
          0.99999917]),
 array([256.07443284, 337.36599425, 274.76709633, 356.05865774,
          0.99999928]),
 array([256.19035134, 337.39452693, 274.64857039, 355.85274598,
          0.99999952]),
 array([256.20705602, 337.51512173, 274.48279087, 355.79085658,
          0.99999952]),
 array([256.45405223, 337.8967452 , 274.7608741 , 356.20356707,
          0.99999869]),
 array([256.48684501, 337.88124316, 274.70912481, 356.10352296,
          0.9999994 ]),
 array([255.31912933, 337.305106